# This file tells Netlify how to build your site.
# It overrides the settings in the Netlify UI.

[build]
  # The command to run to build your site.
  command = "npm run build"

  # The folder to deploy (relative to the root of your project).
  publish = "public"

  # The functions folder (good to have for the future).
  functions = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
