# This configuration assumes it lives at the repository root
# and that the Netlify UI build settings are BLANK.

[build]
  # Tell Netlify where the final, built site will be,
  # relative to the repository root.
  publish = "cozy-home-blog copy/public"

  # Define the full command to build the site.
  # 1. cd into the project sub-folder.
  # 2. Run the build script.
  command = "cd 'cozy-home-blog copy' && npm run build"

# This rule makes sure that the Netlify CMS admin panel works correctly.
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
