# This configuration is at the root of the repository.

[build]
  # The "base" directory tells Netlify to change into this folder before running any commands.
  base = "cozy-home-blog copy"

  # The "publish" directory is relative to the "base" directory.
  publish = "public"

  # The build command will be run from inside the "base" directory.
  command = "npm run build"

# This rule makes sure that the Netlify CMS admin panel works correctly.
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
