backend:
  name: git-gateway
  branch: main # Branch where your content if you set up specific preview styles)
    fields: # The fields for each document, usually in front matter and body
      - {label: "Title", name: "title", widget: "string", required: true}/uploads" # Folder where uploaded files will be stored
public_folder: "/assets/uploads" # The path to the folder on your deployed site

collections:
  - name: "posts" # Used in routes, e is stored. Change to 'master' if that's your default.

publish_mode: editorial_workflow # Recommended for review process, set to 'simple' for direct publish
media_folder: "cozy-home-
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, picker_utc: true, required: true}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Featured Image", name: "image", widget: "image", required:.g., /admin/#/collections/posts
    label: "Cozy Stories" # The name in the UI
    # === THIS LINE IS CHANGED ===
    folder: "cozy-home-blog copy/src/_posts" #blog copy/public/assets/uploads" # Folder where uploaded files will be stored
public_folder: "/assets/uploads" # The path to the folder on your deployed site

collections:
  - name: "posts" # Used in routes, e.g., /admin/#/collections/posts
    label: "Cozy Stories" # The name in the UI
    # === CHANGE THIS LINE ===
    folder: "cozy-home-blog copy false}
      - {label: "Image Alt Text", name: "imageAlt", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false, default: ["cozy"]}
      - {label: "Body", name: "body", widget: "markdown", required: true}
